kind = "mobile"
previewPath = "/vermifert-mobile/"
title = "Vermifert Mobile"
version = "1.0.0"
id = "artifacts/vermifert-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/vermifert-mobile/" ]
localPort = 24365

[services.development]
run = "pnpm --filter @workspace/vermifert-mobile run dev"

[services.production.build]
args = ["pnpm", "--filter", "@workspace/vermifert-mobile", "run", "build"]

[services.production.build.env]
NODE_ENV = "production"

[services.production.run]
args = ["pnpm", "--filter", "@workspace/vermifert-mobile", "run", "serve"]

[services.production.run.env]
PORT = "24365"
BASE_PATH = "/vermifert-mobile/"
NODE_ENV = "production"

[services.env]
PORT = "24365"
BASE_PATH = "/vermifert-mobile/"
